apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-api
spec:
  selector:
    matchLabels:
      app: basic-api
  template:
    metadata:
      labels:
        app: basic-api
    spec:
      containers:
      - name: basic-api
        image: basic-api:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: "onCallApi"
          value: "http://oncall-api-service"
        - name: ConnectionStrings_basic
          value: 'server=sql-service;user=sa;password=TokyoJoe138!;database=basic_prod'
        # name: ASPNETCORE_DEVELOPMENT
        # value:Development
